sudo: false
dist: trusty
#warnings_are_errors: false

os: linux
language: cpp
compiler: clang

git:
  depth: 10

addons:
  apt:
    packages:
      - libopencv-dev

before_install:
  - sudo apt-get update

before_script:
  

install:
  - git clone https://github.com/Itseez/opencv.git
  - cd opencv
  - git checkout $"3.4.2"
  - mkdir build
  - cd build
  - cmake ..
  - make -j4
  - sudo make -j4 install
  - cd ../..
  - mkdir bin
  - ls
  - cmake ../ -DWITH_WARNINGS=1 -=0 -DCMAKE_BUILD_TYPE=Debug -DCMAKE_C_FLAGS="-Werror" -DCMAKE_CXX_FLAGS="-w" -DCMAKE_C_FLAGS_DEBUG="-DNDEBUG" -DCMAKE_CXX_FLAGS_DEBUG="-DNDEBUG" 
  - ls
script:
  - $CXX --version
   - cd bin
  - make -j 4 -k && make install